### ISSUE TITLE
Combined nvd3-efforts

### ISSUE THREAD

**Issue by nomego** [saeidzebardast/nvd3-elements#1]
Hi!

I would like to propose that we combine our development efforts with nvd3 Polymer elements!

We've published an nvd3-pie element at https://github.com/Neovici/nvd3-pie with a different feature set but the same general goal.

The things we would want to get into your behavior or specific elements would be:

- [x] Possibility to (multi) select graph slices/parts (with bound `selected` or similar and/or events)
- [x] Configurable x/y label/value properties (to avoid re-mapping input data)
- [x] Support title
- [x] Support tooltips
- [x] Support growOnHover

Also I would probably consider using `iron-resize` and `refresh()` method instead of `nv.utils.windowResize()` helper to also react on resize-events within the page and not only the window.

If you think these are features/changes you'd welcome into your repository we can fork your repo and start working on PRs for this.
Any feature you'd want to implement yourself of these?
They are available (although they can be made more elegant) in our element right now if you want to have a look.

Thanks and hope we can work together on this!

**Comment by saeidzebardast** [comment]
Dear Patrik,

Thank you for your suggestions. I've implemented the following features based on your request and released v0.13.0:

- title (nvd3-donut)
- growOnHover (nvd3-pie, nvd3-donut)

For other features, you're welcome to open pull requests. I'll merge them ASAP.
I hope we can work together on this to implement more features.

**Comment by nomego** [comment]
Great!

We'll get working on PRs soon, probably tomorrow or next week!

**Comment by saeidzebardast** [comment]
All features are available on 0.17.1.
