### ISSUE TITLE
Events from Tooltip/ DataPoint

### ISSUE THREAD

**Issue by senfgurke** [saeidzebardast/nvd3-elements#10]
First of all, great work.... the nvd-elements are handy and sweet..

But some events from the charts outside of the component would be nice...

Szenario: onMouseover a dataPoint I need to draw this data into a map, but I didn't know how to listen on these Events...

**Comment by saeidzebardast** [comment]
I'm happy to see the nvd3-elements are useful :smiley: 
You could create listeners for NVD3 events. e.g.  chartClick, elementClick, elementDblClick and etc.
Check the following link to see the list of events per chart:
https://nvd3-community.github.io/nvd3/examples/documentation.html
