### ISSUE TITLE
Using "dom: 'shadow'" option in polymer invalidates the css styles

### ISSUE THREAD

**Issue by javiercbk** [saeidzebardast/nvd3-elements#11]
The [polymer documentation](https://www.polymer-project.org/1.0/docs/devguide/settings) states:

> shadow. Local DOM is rendered using shadow DOM where supported (this will be the default in the future).

Setting the dom global variable to shadow breaks all the css styles and rules.
`window.Polymer = {dom: 'shadow'};`

**Comment by saeidzebardast** [comment]
Add `::shadow` to [nvd3-shared-styles.html](https://github.com/saeidzebardast/nvd3-elements/blob/master/nvd3-shared-styles.html) selectors fix many issues but some issues such as background of tooltip box aren't fixed.

**Comment by saeidzebardast** [comment]
Fixed at [v0.19.0](https://github.com/saeidzebardast/nvd3-elements/releases/tag/v0.19.0).
