### ISSUE TITLE
Using a chart inside iron-collapse causes unecessary refresh 

### ISSUE THREAD

**Issue by plequang** [saeidzebardast/nvd3-elements#14]
When using an `nvd3-pie` or `nvd3-donut` element within an `iron-collapse` element, the chart element receive `iron-resize` events when we mouse hover the chart.

This is because `iron-collapse` fires `iron-resize` events when it receives `transitionend` events.

Donut and pie charts use css transitions to change the opacity of the chart slices, causing a transitionend event to bubble up to iron-collapse.

This is not a nvd3-elements issue, but  maybe nvd3-elements could provide a workaround to avoid this (by stopping transitionend events propagation).

I will submit a PR, let me know if you think it's relevant.

**Comment by saeidzebardast** [comment]
Thanks for PR. I've merged it.
