### ISSUE TITLE
Chart elements cannot be styled by CSS

### ISSUE THREAD

**Issue by n1ywb** [saeidzebardast/nvd3-elements#17]
Chart elements cannot be styled by CSS

When a non-polymer lib (e.g. d3) makes DOM changes it is necessary to call `scopeSubtree` to update the classes. This is documented at https://www.polymer-project.org/1.0/docs/devguide/styling#scope-subtree

We do call `scopeSubtree` at https://github.com/saeidzebardast/nvd3-elements/blob/master/nvd3-behavior.html#L317 however ~~this is insufficient because the local DOM continues to change after ready, e.g. when data arrives or changes.~~ something is triggering D3 to unconditionally overwrite the class attribute on certain SVG elements immediately after the mutationObserver finishes setting them all, undoing some of it's work.

In this screenshot note the `<rect>` and the enclosing `<g>` are missing the `style-scope nvd3-discrete-bar style-scope` classes; without these classes it's IMPOSSIBLE to style them with CSS in Polymer. Add those classes manually and suddenly style sheets work as expected.

![image](https://cloud.githubusercontent.com/assets/316961/21295719/3f4b54ae-c529-11e6-8c9d-1c830eb0d864.png)

~~The fix is to call       `this.scopeSubtree(this.$.svg, true);` whenever nvd3/d3 adds DOM elements.~~ (scopeSubtree sets up a mutationObserver that is supposed to keep the classes up to date with subsequent mutations.)

**Comment by n1ywb** [comment]
It happens here https://github.com/novus/nvd3/blob/master/src/models/discreteBar.js#L179

![image](https://cloud.githubusercontent.com/assets/316961/21356272/04aaa422-c69f-11e6-8418-a8c637f83238.png)

**Comment by saeidzebardast** [comment]
This is NVD3 bug and needs to be fixed on its own repository.
