### ISSUE TITLE
Support for x axis labels

### ISSUE THREAD

**Issue by javiercbk** [saeidzebardast/nvd3-elements#9]
Currently the element only supports numbers as the only x axis value. It would be sweet if this element supports labels in the x axis as [this](http://stackoverflow.com/questions/24858382/how-to-add-string-values-to-nvd3-line-chart-x-axis-values) stackoverflow answer points out.

**Comment by saeidzebardast** [comment]
I'll work on this issue next week.

**Comment by saeidzebardast** [comment]
@javiercbk I've fixed this issue for line and area charts. You need to use v0.18.0.
Now, you could set xAxisLabels for the following charts:

- `<nvd3-line>`
- `<nvd3-line-with-focus>`
- `<nvd3-stacked-area>`
- `<nvd3-cumulative-line>`

See [the component page](http://saeidzebardast.github.io/nvd3-elements/components/nvd3-elements/#nvd3-line) for new demo and options.
